---
# tasks file for elastic
- name: Add variables
  include_vars: main.yml

- name: Add elasticsearch key
  raw: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add repo
  template:
    src: templates/elastic-repo.j2
    dest: /etc/yum.repos.d/elastic-repo.repo

- name: Install elasticsearch
  dnf: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ packages }}"

- name: Allow firewalld
  firewalld:
    port: "{{ ports_elastic_firewall }}"
    state: enabled
    permanent: yes
    immediate: yes

- name: Start service
  service:
    name: "{{ item.name }}"
    state: started
    enabled: yes
  loop: "{{ services }}"

