---
# tasks file for elastic
- name: Add variables
  include_vars: main.yml

- name: Add repo
  template:
    src: templates/elastic-repo.j2
    dest: /etc/yum.repos.d/elastic-repo.repo

- name: Install elasticsearch
  dnf: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ packages }}"

- name: Start service
  service:
    name:
    state: started
    enabled: yes