---
- name: set defatul target
  hosts: all
  tasks:
    - name: link the target 
      file:
        state: link
        src: /usr/lib/systemd/system/multi-user.target
        dest: /etc/system/system/default.target